apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: machines-endpoints
  namespace: monitoring
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: machines-endpoints
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machines-endpoints
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
